name: Cypress Tests (Realworld App)

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      # Install app dependencies
      - name: Install dependencies
        working-directory: ./cypress-realworld-testing-course-app
        run: npm ci

      # Build Next.js app for production
      - name: Build app
        working-directory: ./cypress-realworld-testing-course-app
        run: npm run build

      # Start Next.js production server in the background (bind to all interfaces)
      - name: Start app
        working-directory: ./cypress-realworld-testing-course-app
        # Use next start flags to bind host and port explicitly and background the process
        run: npm run start -- -p 3000 -H 0.0.0.0 &

      # Wait until it's reachable
      - name: Wait for app
        run: npx wait-on http://localhost:3000 --timeout 60000

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./cypress-realworld-testing-course-app
          browser: chrome
