name: Cypress Tests (Realworld App)

on:
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install app dependencies
      - name: Install dependencies
        working-directory: ./cypress-realworld-testing-course-app
        run: npm ci

      # Start Next.js app
      - name: Start app
        working-directory: ./cypress-realworld-testing-course-app
        run: npm run dev &

      # Wait until it's reachable
      - name: Wait for app
        run: npx wait-on http://localhost:3000

      # Run Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: ./cypress-realworld-testing-course-app
          browser: chrome
